[ERROR] (tests/ex29_tests.c:27: errno: None) Function fail_on_purpose return 1 for data: I fail with length of 6
